name: Build and test

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

env:
    # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
    BUILD_TYPE: Release

jobs:
    build:
        # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
        # You can convert this to a matrix build if you need cross-platform coverage.
        # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Cache packages
              id: cache-packages
              uses: actions/cache@v2
              with:
                  path: /var/cache/apt/archives
                  key: ${{ runner.os }}-packages-${{ hashFiles('**/packages.txt') }}
                  restore-keys: ${{ runner.os }}-packages-

            - name: Download packages
              if: steps.cache-packages.outputs.cache-hit != 'true'
              run: sudo apt-get update -y && sudo apt-get install -y $(cat ${GITHUB_WORKSPACE}/packages.txt)

            - name: Check format
              run: ${{github.workspace}}/scripts/check_format.sh

            - name: Run pmccabe
              run: ${{github.workspace}}/scripts/cabe.sh

            - name: Configure CMake
              run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

            - name: Build
              run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

            - name: Test
              working-directory: ${{github.workspace}}/build
              run: ctest -C ${{env.BUILD_TYPE}}
